=== 2526-LM-1DW3A-Reto2/LM_Grupo2/HTML/xml/general/general.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    
    <xs:element name="federacionBalonmano">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="temporadas">
                    <xs:complexType>
                        <xs:sequence>

                            <!-- Temporada -->
                            <xs:element name="temporada" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>

                                        <!-- Equipos -->
                                        <xs:element name="equipos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="equipo" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="escudo">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- Jornadas -->
                                        <xs:element name="jornadas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="jornada" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="partidos">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="partido" maxOccurs="unbounded">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="golesLocal" type="xs:nonNegativeInteger"/><!--El tipo de type son números enteros y no puede ser negativos-->
                                                                                        <xs:element name="golesVisitante" type="xs:nonNegativeInteger"/>
                                                                                        <xs:element name="estado">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction base="xs:string">
                                                                                                    <xs:enumeration value="jugado"/>
                                                                                                    <xs:enumeration value="pendiente"/>
                                                                                                    <xs:enumeration value="suspendido"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="id" type="xs:ID" use="required"/><!--id se define como xs:ID porque identifica de forma única -->
                                                                                    <xs:attribute name="local" type="xs:IDREF" use="required"/><!--Se usa xs:anyURI porque el atributo url almacena direcciones de recursos válidas-->
                                                                                    <xs:attribute name="visitante" type="xs:IDREF" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- Jugadores -->
                                        <xs:element name="jugadores">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="jugador" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="altura" type="xs:decimal"/>
                                                                <xs:element name="peso" type="xs:decimal"/>
                                                                <xs:element name="dorsal" type="xs:positiveInteger"/><!--El tipo de type solo permite números enteros-->
                                                                <xs:element name="foto">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                                            <xs:attribute name="equipo" type="xs:IDREF" use="required"/> <!--equipo se define como xs:IDREF porque referencia al identificador de un equipo existente-->
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <!-- Clasificación -->
                            <xs:element name="clasificacion" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 2526-LM-1DW3A-Reto2/LM_Grupo2/HTML/xml/general/general.xml
<?xml version="1.0" encoding="UTF-8"?>
<federacionBalonmano xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="general.xsd">

    <temporadas>
        <temporada id="2021_2022">
            <equipos>
                <equipo id="E001">
                    <nombre>FC Barcelona</nombre>
                    <escudo url="./imagenes/imagenes_Logos/BARCELONA.png"/>
                </equipo>
                <equipo id="E002">
                    <nombre>Zaragoza BM</nombre>
                    <escudo url="./imagenes/imagenes_Logos/ZARAGOZABM.png"/>
                </equipo>
                <equipo id="E003">
                    <nombre>Valencia HC</nombre>
                    <escudo url="./imagenes/imagenes_Logos/VALENCIA.png"/>
                </equipo>
                <equipo id="E004">
                    <nombre>Vigo BM</nombre>
                    <escudo url="./imagenes/imagenes_Logos/VIGO.png"/>
                </equipo>
                <equipo id="E005">
                    <nombre>Sevilla BM</nombre>
                    <escudo url="./imagenes/imagenes_Logos/SEVILLABM.png"/>
                </equipo>
                <equipo id="E006">
                    <nombre>Bilbao HC</nombre>
                    <escudo url="./imagenes/imagenes_Logos/BILBAO.png"/>
                </equipo>
            </equipos>
            <jornadas>
                <jornada id="J001">
                    <partidos>
                        <partido id="P1_1" local="E001" visitante="E005">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P1_2" local="E002" visitante="E004">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P1_3" local="E003" visitante="E006">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J002">
                    <partidos>
                        <partido id="P2_1" local="E005" visitante="E004">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P2_2" local="E001" visitante="E003">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P2_3" local="E006" visitante="E002">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J003">
                    <partidos>
                        <partido id="P3_1" local="E004" visitante="E003">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P3_2" local="E005" visitante="E006">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P3_3" local="E002" visitante="E001">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J004">
                    <partidos>
                        <partido id="P4_1" local="E003" visitante="E006">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P4_2" local="E004" visitante="E002">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P4_3" local="E001" visitante="E005">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J005">
                    <partidos>
                        <partido id="P5_1" local="E006" visitante="E001">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P5_2" local="E003" visitante="E005">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P5_3" local="E002" visitante="E004">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J006">
                    <partidos>
                        <partido id="P6_1" local="E005" visitante="E001">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P6_2" local="E004" visitante="E002">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P6_3" local="E006" visitante="E003">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J007">
                    <partidos>
                        <partido id="P7_1" local="E004" visitante="E005">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P7_2" local="E003" visitante="E001">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P7_3" local="E002" visitante="E006">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J008">
                    <partidos>
                        <partido id="P8_1" local="E003" visitante="E004">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P8_2" local="E006" visitante="E005">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P8_3" local="E001" visitante="E002">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                    </partidos>
                </jornada>
                <jornada id="J009">
                    <partidos>
                        <partido id="P9_1" local="E006" visitante="E003">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P9_2" local="E002" visitante="E004">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
                            <estado>Sin jugar</estado>
                        </partido>
                        <partido id="P9_3" local="E005" visitante="E001">
                            <golesLocal>0</golesLocal>
                            <golesVisitante>0</golesVisitante>
